### PR TITLE
Change web to "Web", except for "website".

### PR DESCRIPTION
**Pull request by prushforth**
It was inconsistent before, and I like to think of the Web as a thing, especially in contrast with proprietary platforms.

### CODE REVIEW

**Comment by AmeliaBR** [comment]
No problem with the style changes.

Adding heading IDs is great, too. I've been trying to do that myself.

But hard coding the heading self-links is not great for a dynamic site, as it means things could get out of sync later and we could end up with an inconsistent site. I did some digging and the alternatives are either: [client-side JS](https://github.com/bryanbraun/anchorjs#installation) or some brilliant but nasty [regex-based template manipulation](https://github.com/allejo/jekyll-anchor-headings). My preference is to do it during the static site build, so the second option ("jekyll-anchor-headings" snippet) looks best. It does seem to be well tested & widely used, although the liquid code is beyond my ability to review.

@nchan0154 Opinions on this, since you have more Jekyll experience than I do?

**Comment by Malvoz** [comment]
The hard coded self-links are pointing to IDs of hard coded headings, so that should be fine. anchorJS seems nice though, as it removes the labor of manually creating and maintaining the self-links.

**Comment by nchan0154** [comment]
Quick and dirty third option, I noticed the Transport Workshop that Amelia linked for reference also has a [snippet](https://www.w3.org/auto/events/data-ws-2019/assets/js/script.js) to do this, and the stylesheet is already taken care of!

**Comment by prushforth** [comment]
Oh yeah I should have mentioned that's where I got the HTML for this from.

**Comment by AmeliaBR** [comment]
OK, I have merged in the 'Change web to "Web", except for "website".' commit manually, so I'm closing this PR.

You can open a separate PR for adding IDs if I've missed any once I merge the CFP edits I was working on. For the heading self-links, I think it is best to use the JS snippet to add the repeated markup automatically.

For future reference, please try to remember to use feature branches so that you don't end up with unrelated commits in a PR just because someone else (ahem, sorry) was a little slow in merging!

**Comment by nchan0154** [comment]
@prushforth let me know if you'd like me to take on the task of adding the JS snippet, it should be simple enough to modify it so it generates the IDs automatically as well, if you'd like all headings to have links.

Edit: Realized I foot-in-mouth'ed this as obviously, JS generated IDs don't work for same page links due to being loaded in later 😂

**Comment by prushforth** [comment]
Hi @nchan0154 Sure that would be great!  I didn't notice, when I first started copying their work, that they used script to generate stuff.  Automation is always better for consistency!  Thank you.

**Pull request closed without merging**
