### PR TITLE
Agenda Cleanup

### PR DESCRIPTION
**Pull request by nchan0154**
Added most presentations in PDF format (#117)
Updated discourse links to be unique (better for a11y)
Add links to captions HTML

### CODE REVIEW

**Comment by Malvoz** [comment]
@nchan0154 You can mark WIP PRs as Draft, thus they cannot be merged until you mark them as Ready for review. 🙂

**Comment by nchan0154** [comment]
I've also restructured the headers a bit to accommodate for captions as it felt like the h3 elements were doing a bit too much there. 
mapheaders

I'm working through proof reading the captions quickly (imperfect but at least a bit more understandable and focusing on fixing up key abbreviations like W3C and OGC), so @tguild can reupload them to youtube when I'm done processing.

@AmeliaBR This is ok to be reviewed now, I can correct the captions as I go along.

**Comment by nchan0154** [comment]
@tguild I noticed the repository is missing VTT captions for Sept 28, if you could add it to the repo I can also correct these. Thank you!

**Comment by AmeliaBR** [comment]
Ah, sorry, I missed this turning from WIP to “please review”. Everything looks great & much appreciated!

I'll merge what you've got so far, any further cleanup will be great when you get to it. @tguild is probably busy with TPAC this week but I'm sure can take over the captions when he has a moment to breathe.

**Pull request merged**
