### PR TITLE
Add and link Dan Little and Peter Rushforths slides 2020-09-21

### PR DESCRIPTION
**Pull request by prushforth**

### CODE REVIEW

**Comment by Malvoz** [comment]
@prushforth These links resolve to `https://www.w3.org/supporting-material-uploads/...` as opposed to `https://www.w3.org/2020/maps/supporting-material-uploads/...`.

**Comment by prushforth** [comment]
Ok thanks, I'll deal with shortly. Out apple 🍎 picking now while the sun shines.

**Comment by prushforth** [comment]
@nchan0154 can you verify if I solved this and didn't create other problems? It looks like there are other link types that also need {{ relBase }} added, I won't do that until you confirm that's the way you want this done.  Cheers!

**Comment by AmeliaBR** [comment]
The template change (from e2989b5913786c7d59014b0b9bd5110dd1fbf13e ) will work if all the links are relative, but will break if we have any slides links that link out to other websites. But it has fixed the issue for now…

**Comment by nchan0154** [comment]
I was going to put the full canonical link instead of a relative link, but I suppose we can add a check if the URL contains http and not include relBase if the link appears to be external 😂 We have currently not added any other slide links, so no worries about breaking there.

**Pull request merged**
