### PR TITLE
Convert report to template

### PR DESCRIPTION
**Pull request by nchan0154**
I've replaced the existing [ /report](https://maps4html.org/Maps4HTML-Workshop-2020/report) page with the draft report.md file, then bumped up all the headings so that h3 -> h2 and etc. to match the template heading structure. The file, now located in the root directory at report.md, is still in markdown so hopefully can still be edited by whoever needs to.

[Preview link for the changes](https://nchan0154.github.io/Maps4HTML-Workshop-2020/report)

@tguild @prushforth @AmeliaBR

### CODE REVIEW

**Comment by prushforth** [comment]
There seems to be an extra line break in the paragraph beginning with Kathi Schleidt, although it obviously is due to the embedded link and is there in the original.  I don't suppose there's any way to fix that. 

Would it be possible to add ids to people's names, so that they can be referenced with a hyperlink?  I could do that if you recommend a way, as I realize I could have done that before.  Maybe `<span id="pr">Peter Rushforth</span>` is the way?

**Comment by Malvoz** [comment]
> There seems to be an extra line break in the paragraph beginning with Kathi Schleidt

Removing this declaration fixes it (not 100% sure why it causes it):

https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/blob/63f1290ce939b44fdfe513ca200952fec7d51c7d/assets/css/style.css#L28

but maybe that's useful somewhere else?

**Comment by AmeliaBR** [comment]
The no-hyphens style seems to go back to the original import (according to [git blame](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/blame/4d92b9c119ee04e633e691cde3719304517dcac3/assets/css/style.css#L33)), so it wasn't an intentional choice by any of us. Should be OK to switch to auto hyphens, though maybe want to restrict that to the `<main>` region to minimize layout weirdness caused by shrinking the min-content width in flex/grid layout sections.

We already use a short [client-side script](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/blob/master/assets/js/script.js) to inject anchors for headings, it should be fairly easy to expand that to include other markup you want to be able to jump to. But if you just want to highlight every instance of a name, that might be easier to do in the build rather than adding markup to the markdown. There's already a [data file of participants](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/blob/master/_data/participants.yml) so that could be imported and the entire content run through a custom layout to do the substitutions.

But... I'm not certain whether it would be worth the effort. Do you want to maybe open an issue on that, @PRushforth, where you can sketch out how you want to use these links & what sort of cross-references you'd want to generate from/to other parts of the website?

Otherwise, I'd say it's best to merge this PR immediately, so that people can continue editing the draft without causing merge conflicts later. (I almost did this myself, starting a copy-edit of the other report.md file. But my browser reloaded & lost those changes anyway, so the merge conflicts will only exist in my ability to remember what I'd written!)

**Comment by prushforth** [comment]
Links to names are just a convenience facility for people (like me 😄 ) to share a link to a particular specific talk or quote.  I sometimes use the browser context menu inspect option to see if there's an id on something nearby to make a url for sharing.  I don't foresee a need for cross-references. That's all. Go ahead and merge this PR.  I've been selecting images from the workshop if these are of interest, I think it might make the report too heavy, and we may need to generate images for phones/responsive images if we go too far down this [path](https://docs.google.com/document/d/1bN3nvSPuzHJK1J8EQJyAzWffB1mx_SIiY9D1p7HPmKo/edit), opinions/ideas welcome!

**Comment by Malvoz** [comment]
Off-topic:

> to make a url for sharing

@prushforth quite a few browsers already [support](https://caniuse.com/url-scroll-to-text-fragment) [scroll-to-text fragments](https://wicg.github.io/scroll-to-text-fragment/), which you may find useful. Here's a test URL:

https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/blob/master/supporting-material-uploads/report/report.md#:~:text=peter%20rushforth 😄

**Pull request merged**
