### PR TITLE
Update Brandon B's talk title, add link to external resource for his breakout

### PR DESCRIPTION
**Pull request by prushforth**
@nchan0154 is this how you would link to stuff?   Where do presentations go (what folder?) if we are going to host them?  How would you link to or yaml that?

### CODE REVIEW

**Comment by nchan0154** [comment]
I've pulled out the link to use YAML instead of straight HTML in case we need to change the display later. My initial thought was that we could put presentation materials in a new subfolder of the supporting-material-uploads folder but I imagine things like video and numerous presentations may cause the repository to surpass the GitHub limit. Is there a W3C designated storage space for such materials? @prushforth

**Comment by prushforth** [comment]
> Is there a W3C designated storage space for such materials?

@tguild  can you help us with uploading presentation materials and providing links to us that we can link to from the agenda, please?

**Comment by tguild** [comment]
@nchan0154 do create subfolder for presentations. I'll look for details on where we are sending videos these days.

**Comment by tguild** [comment]
We have used a couple different platforms, for workshop presentation videos we can use https://www.youtube.com/c/W3COfficial 

@nchan0154 if you park videos (and captions) somewhere I can upload them

**Pull request merged**
