### PR TITLE
Agenda import

### PR DESCRIPTION
**Pull request by nchan0154**
Apologies for the duplicate PR, I do not have write access to the repository. I have formatted the draft agenda in #65. (do not worry, I used regex so it didn't take that long!) 

I have attached a screenshot of the current agenda with all the collapsible elements uncollapsed for those who are unable to run the build locally. 

## Questions
- I believe we are missing a plenary title on September 28, what should this be called
- Will we add timestamps eventually? If not, should I revise the styling to remove the timestamp space?

<details>
<summary>Screenshot of the agenda</summary>

</details>

@AmeliaBR @prushforth @tguild

### CODE REVIEW

**Comment by prushforth** [comment]
@nchan0154  @AmeliaBR @tguild I've edited the spreadsheet entitle "Schedule" to add the missing talks and add times for Sept 30, Oct 1/2.  

> I believe we are missing a plenary title on September 28, what should this be called

There is a title in the spreadsheet, maybe that got edited post-export.

> Will we add timestamps eventually? If not, should I revise the styling to remove the timestamp space?

There are rough time stamps in the spreadsheet, we should start with these, at least the daily zoom will have a start and end time.

Since I edited the spreadsheet, not @tguild 's PR, maybe we should re-export the "Schedule" spreadsheet, somehow, someway (cf. Tom Waits)

**Comment by nchan0154** [comment]
Great, I will update the PR with the changes to the schedule tomorrow, thanks Peter!

**Comment by prushforth** [comment]
Thanks Nic!

**Comment by AmeliaBR** [comment]
OK, first thing first, I bumped Nic's permissions on the repo to write, so you can make changes to other people's PRs and/or merge them in the future.

But don't do that right now, because I'm about to start working on it myself.

**Comment by AmeliaBR** [comment]
Important! (And sorry for not noticing this sooner…)

The times currently in the spreadsheet are not the ones I'd recommended in my email — for North America, they are Sunday to Thursday, and I thought we'd agreed to try to keep everything Monday to Friday.

Was this intentional or accidental, @tguild ?  (I assume accidental, you used my time slots A to D, from earliest to latest UTC time in order, but that didn't work with the “weekdays only” constraint.)

But… @prushforth has now been doing tweaks and adjustments based on these times & the resulting conflicts for speakers, so do we re-do that, or do we accept that the workshop will start on Sunday evening for western hemisphere speakers?

**Comment by prushforth** [comment]
I am OK with Sunday evening. I think Ted and I were aware of that as we did the spreadsheet.

**Comment by AmeliaBR** [comment]
OK, that's easiest anyway. (And I *personally* am happier to do my talk Sunday evening than very early Monday morning). Sorry for the late panic!

**Comment by nchan0154** [comment]
> But don't do that right now, because I'm about to start working on it myself.

@AmeliaBR Do you mean this PR or the repo in general?

**Comment by AmeliaBR** [comment]
This PR! I'm busy fixing up these templates to work better for the online schedule. (currently trying to make sense of all the extra CSS on top of details/summary…)

If you want to go ahead with posting position statements or other things, that should be fine. Just don't mess with this page right now.

**Comment by AmeliaBR** [comment]
OK, I pushed what I was working on, still want to do some more before merging, but I'd appreciate any feedback on the new design/organization.

PS, screenshots of new design, for those who don't have the build set up:

<details>
<summary>Mobile layout</summary>

Screenshot

</details>

<details>
<summary>Wider-screen layout</summary>

Screenshot, with a little more whitespace and blue margins


</details>

**Comment by prushforth** [comment]
So it looks nicely formatted. We are [still missing](https://github.com/Maps4HTML/Maps4HTML-Workshop-2020/pull/66#issuecomment-674396037) the talks from the "Schedule" spreadsheet, which were somehow omitted when that sheet was created.  In brief: the schedule for Sept 30 and Oct 1st is incorrect.

**Pull request merged**
